/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.FCPagina;
import Model.EntityObject.Acquisizione;
import Model.EntityObject.Opera;
import Model.EntityObject.Pagina;
import Model.EntityObject.Utente;
import View.V_Acquisizione;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.HashMap;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gianluca
 */
public class Editor extends javax.swing.JFrame {
    private Pagina pagina;
    private Opera opera;
    private Acquisizione acquisizione;
    private V_Acquisizione view;
    private ImageIcon bg;
    private Utente utente;
    private Pannello_trascrittore _prev;
    private Trascrittore_pagine prev;
    private FCPagina controllerP;
    /**
     * Creates new form Mostra_Acquisizione
     */
    public Editor(Pagina a, FCPagina cp, Utente ut, Trascrittore_pagine pr, Opera op) throws IOException {
        this.utente = ut;
        this.pagina = a;
        this.opera = op;
        this.acquisizione = a.getAcquisizione();
        this.prev = pr;
        this._prev = null;
        this.controllerP = cp;
        this.view = cp.ask(ut, this.acquisizione);
        Image image = ImageIO.read(this.view.getInput()).getScaledInstance(425, 490,  java.awt.Image.SCALE_SMOOTH);
        this.bg = new ImageIcon(image);
        initComponents();
        myInitComponents();
    }
    
    public Editor(Pagina a, FCPagina cp, Utente ut, Pannello_trascrittore pr, Opera op) throws IOException {
        this.utente = ut;
        this.pagina = a;
        this.opera = op;
        this.acquisizione = a.getAcquisizione();
        this._prev = pr;
        this.prev = null;
        this.controllerP = cp;
        this.view = cp.ask(ut, this.acquisizione);
        Image image = ImageIO.read(this.view.getInput()).getScaledInstance(425, 490,  java.awt.Image.SCALE_SMOOTH);
        this.bg = new ImageIcon(image);
        initComponents();
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editor");
        setResizable(false);

        jLabel1.setIcon(bg);
        jLabel1.setText("");
        jScrollPane1.setViewportView(jLabel1);

        jScrollPane2.setViewportView(jEditorPane1);

        jButton1.setText("Trascrivi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Più tardi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jProgressBar1.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jEditorPane1.getText() != null) {
            setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
            Object[] param = {jEditorPane1.getText(), this.pagina, this.utente, this.opera};
            HashMap<String, Object[]> tras = new HashMap<String, Object[]>();
            tras.put("trascrivi", param);
            MyThread progress = new MyThread(jProgressBar1);
            progress.start();
            if (this.controllerP.doOperation(tras).equals("true")) {
                setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                JOptionPane.showMessageDialog(jFrame1, "Trascrizione avvenuta correttamente!");
            } else {
                setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                JOptionPane.showMessageDialog(jFrame1, "Errore durante la trascrizione"); 
            }
            this.dispose();
            Pannello_trascrittore new_p = new Pannello_trascrittore
            (this.controllerP.askOpere(this.utente, "acquisito"),
            this.controllerP);
            if (prev != null) {
               Trascrittore_pagine new_tp = new Trascrittore_pagine(this.controllerP.askPagine(this.opera, this.utente), 
               this.controllerP, new_p);
               if (new_tp.sizeList()>0) {
                    new_tp.setVisible(true);  
               } else {
                    new_p.setVisible(true);
               }
               prev.dispose();
            } else {
               new_p.setTable(1);
               new_p.setVisible(true);
               _prev.dispose();
            }        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        Pannello_trascrittore new_p = new Pannello_trascrittore
        (this.controllerP.askOpere(this.utente, "acquisito"),
        this.controllerP);
        if (prev != null) {
            Trascrittore_pagine new_tp = new Trascrittore_pagine(this.controllerP.askPagine(this.opera, this.utente), 
            this.controllerP, new_p);
               if (new_tp.sizeList()>0) {
                    new_tp.setVisible(true);  
               } else {
                    new_p.setVisible(true);
               }
               prev.dispose();
        } else {
           new_p.setTable(1);
           new_p.setVisible(true);
           _prev.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void myInitComponents() {
        setLocationRelativeTo(null);
        
        if (this.view.getUtente().getRuolo().equals("amministratore")) {
            jButton2.setVisible(false);
            
            addWindowListener(new WindowAdapter()
            {
                @Override
                public void windowClosing(WindowEvent e)
                {
                    controllerP.updateStato(pagina, "acquisito");
                    controllerP.disassign(utente, pagina);
                    e.getWindow().dispose();                   
                }
            });
        }        
    } 
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
